
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <time.h>

#define LEITURA 0
#define ESCRITA 1

#define FILHOS 5



// 11. Write a program that creates 5 child processes. Connect all 
// 6 processes with a “ring” topology through pipes: the parent process 
// will be connected to child 1, child 1 is connected to child 2, ..., 
// and child 5 is connected to the parent process. The goal is to find 
// the greatest random number generated by all processes:
//
// a. Each process generates a random number between 1 and 500. 
//      Then, it prints it along with its PID;
// b.Then, the parent process sends its generated number to child 1; 
//
// c.Child 1 compares the parent’s number with its own random number 
//      and sends the greater of the two to child 2;
// d.All otherprocesses follow the same behavior, until child 5 sends 
//      the greater number to the parent process;
// e.The parent process prints the greatest random number.


// Loop
// Parent -> Child 1 -> Child N -> Child 5 -> Parent


int spawn_childs(int n) {
    int i;
    for (i=1; i<=n; i++) {
        pid_t pid = fork();
        if(pid==-1){
            perror("wait failled!");
            exit(EXIT_FAILURE);
        } 
        if(pid==0) {
            return i;
        }
    }
    return 0;
}

int main() {
    int i;
    
    int fd[FILHOS+1][2];
    for(i=0; i<=FILHOS; i++) {
        if(pipe(fd[i]) == -1) {//cria pipe
            perror("Pipe failed!");
            exit(EXIT_FAILURE);
        }
    }

    int randomGenNumber;
    int prevNodeNumber;

    int nthChild = spawn_childs(FILHOS);
    

    //gera um numero para cada processo
    srand(time(0)+nthChild);
    randomGenNumber = rand()%499 + 1;
    printf("My pid : %d, Random number : %d\n", getpid(), randomGenNumber);

    if(nthChild == 0) {
        close(fd[nthChild][LEITURA]);
        write(fd[nthChild][ESCRITA], &randomGenNumber, sizeof(int));
        close(fd[nthChild][ESCRITA]);

        close(fd[FILHOS][ESCRITA]);
        read(fd[FILHOS][LEITURA], &prevNodeNumber, sizeof(int));
        close(fd[FILHOS][LEITURA]);
        printf("NÚM MAX : %d\n", prevNodeNumber);

    } else {
        close(fd[nthChild-1][ESCRITA]);
        read(fd[nthChild-1][LEITURA], &prevNodeNumber, sizeof(int));
        close(fd[nthChild-1][LEITURA]);
        if(randomGenNumber > prevNodeNumber) {
            prevNodeNumber = randomGenNumber;
        }
        close(fd[nthChild][LEITURA]);
        write(fd[nthChild][ESCRITA], &prevNodeNumber, sizeof(int));
        close(fd[nthChild][ESCRITA]);

        exit(EXIT_SUCCESS);
    }

    
    //Espera pelos filhos
    for(i=0; i<FILHOS; i++) {
        wait(NULL);
    }
    return 0;
}